$script:ProgramDataRoot   = if ([string]::IsNullOrWhiteSpace($env:ProgramData)) { 'C:\ProgramData' } else { $env:ProgramData }
$script:ProgramFilesRoot  = if ([string]::IsNullOrWhiteSpace($env:ProgramFiles)) { 'C:\Program Files' } else { $env:ProgramFiles }
$script:WindowsRoot       = if ([string]::IsNullOrWhiteSpace($env:WINDIR)) { 'C:\Windows' } else { $env:WINDIR }
$script:HunterRoot        = Join-Path $script:ProgramDataRoot 'Hunter'
$script:DownloadDir        = Join-Path $script:HunterRoot 'Downloads'
$script:LogPath            = Join-Path $script:HunterRoot 'hunter.log'
$script:CheckpointPath     = Join-Path $script:HunterRoot 'checkpoint.json'
$script:ResumeScriptPath   = Join-Path $script:HunterRoot 'Resume\hunter.ps1'
$script:SecretsRoot        = Join-Path $script:HunterRoot 'Secrets'
$script:LocalUserSecretPath = Join-Path $script:SecretsRoot 'local-user.secret'
$script:AllUsersStartMenuProgramsPath = Join-Path $script:ProgramDataRoot 'Microsoft\Windows\Start Menu\Programs'
$script:HostsFilePath      = Join-Path $script:WindowsRoot 'System32\drivers\etc\hosts'
$script:TaskbarPinVerbPatterns = @('*Pin to taskbar*', '*taskbarpin*')
$script:TaskbarUnpinVerbPatterns = @('*Unpin from taskbar*', '*taskbarunpin*')
$script:TaskbarStatePollIntervalMs = 300
$script:TaskbarStateTimeoutSec = 6
$script:StartSurfaceReadyTimeoutSec = 5
$script:GitHubApiMaxAttempts = 3
$script:GitHubApiBaseDelaySec = 2
$script:IsHyperVGuest      = $false
$script:ExplorerRestartPending = $false
$script:StartSurfaceRestartPending = $false
$script:ParallelInstallTargets = @()
$script:ParallelInstallJobs = @()
$script:ParallelInstallResults = @{}
$script:PrefetchedExternalAssets = @{}
$script:ExternalAssetPrefetchJobs = @()
$script:AppShortcutSetCache = @{}
$script:ExecutableResolverCache = @{}
$script:ExecutableResolverNextAttemptAt = @{}
$script:WindowsBuildContext = $null
$script:AppRemovalCatalog = $null
$script:IsAutomationRun = $false
$script:DisableIPv6Requested = $false
$script:TaskbarReconcilePending = $false
$script:DefaultTaskbarPinsRemoved = $false
$script:EdgeShortcutsRemoved = $false
$script:PostInstallCompletion = @{}
$script:RunStopwatch = $null
$script:RunInfrastructureIssues = @()
$script:ProgressUiIssueLogged = $false
$script:CurrentTaskLoggedError = $false
$script:CurrentTaskLoggedWarning = $false
$script:SkipAppDownloads = $null
$script:SkipTaskIds     = @()
$script:UiSync        = $null
$script:UiRunspace    = $null
$script:UiPipeline    = $null
$script:CompletedTasks     = @()
$script:FailedTasks        = @()
$script:TaskResults        = @{}
$script:TaskList          = @()
$script:CheckpointAliases  = @{
    'phase1-restore-point'        = 'preflight-restore-point'
    'phase2-dark-mode'            = 'core-dark-mode'
    'phase3-bing-search'          = 'startui-bing-search'
    'phase3-taskbar-search'       = 'startui-search-box'
    'phase3-taskview-button'      = 'startui-task-view'
    'phase3-widgets'              = 'startui-widgets'
    'phase3-end-task'             = 'startui-end-task'
    'phase3-notifications'        = 'startui-notifications'
    'phase4-explorer-home'        = 'explorer-home-thispc'
    'phase4-explorer-onedrive'    = 'explorer-remove-onedrive'
    'phase4-explorer-autodiscovery'= 'explorer-auto-discovery'
}
$script:AppRemovalCatalogPath = Join-Path $script:HunterSourceRoot 'src\Hunter\Config\Apps.json'
$script:CustomAppsListPath = Join-Path $script:HunterRoot 'CustomAppsList.txt'
$script:CustomAppsListPathOverride = $null
$script:OOSUConfigUrl      = 'https://raw.githubusercontent.com/ChrisTitusTech/winutil/d0bde83333730a4536497451af747daba11e5039/ooshutup10_winutil_settings.cfg'
$script:OOSUSha256         = '01d64c068d6b949ff8b919c30d82ae0007ae3ad35006f63f04880005a33d51e9'
$script:TcpOptimizerSha256 = '0a49dc0d2ce725af347df632539b70afcfd22b38e285920b515143332a5511e9'
$script:Autologon64Sha256  = '5d96bbc4e5b726d87c7cf547f5fe98f8f05434ec2130bd60cbf5671fd3a7381b'
$script:FurMarkDownloadUrl = 'https://geeks3d.com/downloads/2025/fm2/2_10_dbc69dd0a08da5ff09169a4fc759ddaa/FurMark_2.10.2_Win64_Setup.exe'
$script:FurMarkDownloadFileName = 'FurMark_2.10.2_Win64_Setup.exe'
$script:FurMarkSha256      = '88C07E0C674676BB486D3D46D73605925983B3AFA8F292A2D9707AD919A3EA9B'
$script:WallpaperSourceUrl = 'https://w.wallhaven.cc/full/85/wallhaven-85vv1y.png'
$script:ResolvedWallpaperAssetUrl = $null
$script:SelfScriptContent  = $null
